name: Docker Build

on:
  push:
    branches:
      - docker_test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfile
          tags: abhicloud11/nginx
      - name: Push image to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: abhicloud11/nginx
          registry: docker.io
          username: ${{ DOCKERHUB_USERNAME }}
          password: ${{ DOCKERHUB_TOKEN }}
