name: Docker Build

on:
  push:
    branches:
      - docker_test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clonning the repo
        uses: actions/checkout@v2
      - name: logging the container registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build & push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: abhicloud11/nginx
